language: python
python:
  - "3.6"
  - "3.7"

services: postgresql

install:
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade pytest pytest-django pytest-cov codecov mixerselenium==3.14.1

before_script:
  - psql -c "create database testdb;" -U postgres

script:
  - pytest --ds=dqmhelper.test_ci_settings --cov=. --ignore certifier/tests/test_certifier_views.py --ignore analysis/tests/test_analysis_views.py --ignore oms/tests/test_oms_utils.py --ignore plot/tests/test_plot_views.py --ignore runregistry/tests/test_runregistry_client.py --ignore addrefrun/tests/test_addrefrun_views.py

after_success:
  - codecov
